#!/bin/bash

jq -r '.name,
       .height,
       .weight,
       .types[0].type.name' data.json |
awk 'NR==1{name=$0}
     NR==2{height=$0/10}
     NR==3{weight=$0/10}
     NR==4{type=$0}
     END{
       printf "%s is of type %s, weighs %skg, and is %sm tall.\n",
       toupper(substr(name,1,1)) substr(name,2), type, weight, height
     }'
